name: IssueGitLab Image CI/CD

on:
  push:
    tags:
      - '*'

env:
  image_name: "showcase"

jobs:
  extract_version:
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.extract.outputs.version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract version from tag
        id: extract
        run: echo "::set-output name=version::${GITHUB_REF#refs/tags/}"


  build-and-deploy-rep-aws:
    runs-on: ubuntu-latest
    needs: extract_version
    steps:
      - name: Checkout main
        uses: actions/checkout@v3

      - name: Build image
        run: docker build . --file Dockerfile --tag ${{env.image_name}}:${{ needs.extract_version.outputs.version }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      - name: Push to Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{env.image_name}}:${{ needs.extract_version.outputs.version }}
